dotnet-portalclientemsdcombr/MSDPortal.Presentatio22n.Web/Models/Forum.cs
//// -----------------------------------------------------------------------
//// <copyright file="Forum.cs" company="Fluent.Infrastructure">
////     Copyright © Fluent.Infrastructure. All rights reserved.
//// </copyright>
////-----------------------------------------------------------------------
/// This is a test file created by Fluent Infrastructure in order to 
/// illustrate its operation.
/// See more at: https://github.com/dn32/Fluent.Infrastructure/wiki
////-----------------------------------------------------------------------

using Fluent.Infrastructure.FluentAttribute;
using Fluent.Infrastructure.FluentModel;
using System;

namespace MSDPortal.Presentation.Web.Models
{
    [FluentMapTo(typeof(ForumForm))]
    public class Forum : BaseEntityClass
    {
        public string Description { get; set; }
        public DateTime UpdateDate { get; set; }
    }

    public class ForumForm : BaseEntityClass
    {
        public string Name { get; set; }
    }
}

dotnet-portalclientemsdcombr/MSDPortal.Presentatio22n.Web/Controllers/ForumController.cs
//// -----------------------------------------------------------------------
//// <copyright file="ForumController.cs" company="Fluent.Infrastructure">
////     Copyright © Fluent.Infrastructure. All rights reserved.
//// </copyright>
////-----------------------------------------------------------------------
/// This is a test file created by Fluent Infrastructure in order to 
/// illustrate its operation.
/// See more at: https://github.com/dn32/Fluent.Infrastructure/wiki
////-----------------------------------------------------------------------

using Fluent.Infrastructure.FluentController;
using MSDPortal.Presentation.Web.Models;

public class ForumController : ControllerBase<Forum, ForumForm>
{
}

dotnet-portalclientemsdcombr/MSDPortal.Presentatio22n.Web/Controllers/HomeController.cs
using System.Web.Mvc;

namespace MSDPortal.Presentation.Web.Controllers
{
    public class HomeController : Controller
    {


        public ActionResult Index()
        {
            //return RedirectToAction("Index", "NaoLogado");
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

dotnet-portalclientemsdcombr/MSDPortal.Presentatio22n.Web/Controllers/ProdutoController.cs
using MSDPortal.Application;
using MSDPortal.Application.Entidades;
using MSDPortal.Domain.Interfaces.Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MSDPortal.Presentation.Web.Controllers
{
    public class ProdutoController : Controller
    {
        private readonly IProdutoRepository _produtoRepository;

        private readonly ProdutoService _produtoService;

        public ProdutoController(IProdutoRepository produtoRepository)
        {
            _produtoRepository = produtoRepository;
        }
        public ProdutoController(ProdutoService produtoService)
        {
            _produtoService = produtoService;
        }
        //public ProdutoController()
        //{
            
        //}
        // GET: Produto
        public ActionResult Index()
        {
            return View();
        }

        // GET: Produto/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Produto/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Produto/Create
        [HttpPost]
        public ActionResult Create(Produto model)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Produto/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Produto/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, Produto model)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Produto/Delete/5
        public ActionResult Delete(int id)
        {

            return View(new Produto());
        }

        // POST: Produto/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, Produto model)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

dotnet-portalclientemsdcombr/MSDPortal.Presentatio22n.Web/Views/Forum/AddReturn.cshtml
@*
////-----------------------------------------------------------------------
//// <copyright file="AddReturn.cshtml" company="Fluent.Infrastructure">
////     Copyright © Fluent.Infrastructure. All rights reserved.
////
//// </copyright>
////-----------------------------------------------------------------------
/// This is a test file created by Fluent Infrastructure in order to
/// illustrate its operation.
/// See more at: https://github.com/dn32/Fluent.Infrastructure/wiki
////-----------------------------------------------------------------------
*@

@using MSDPortal.Presentation.Web.Models
@model ForumForm

@{
    ViewBag.Title = "View";
}

<h2>View</h2>

<div>
    <h4>Forum</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
               
        <dt>
            @Html.DisplayNameFor(model => model.Deleted)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Deleted)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Active)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Active)
        </dd>

    </dl>
</div>

<div>
    @Html.ActionLink("Forum", "New", "Forum")
</div>
<br />
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

dotnet-portalclientemsdcombr/MSDPortal.Presentatio22n.Web/Views/Forum/New.cshtml
@*
////-----------------------------------------------------------------------
//// <copyright file="New.cshtml" company="Fluent.Infrastructure">
////     Copyright © Fluent.Infrastructure. All rights reserved.
////
//// </copyright>
////-----------------------------------------------------------------------
/// This is a test file created by Fluent Infrastructure in order to
/// illustrate its operation.
/// See more at: https://github.com/dn32/Fluent.Infrastructure/wiki
////-----------------------------------------------------------------------
*@

@using MSDPortal.Presentation.Web.Models
@model ForumForm

@{
    ViewBag.Title = "New";
}

<h2>New</h2>

@using (Html.BeginForm(nameof(ForumController.AddReturn), nameof(Forum)))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ForumForm</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Active, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Active)
                    @Html.ValidationMessageFor(model => model.Active, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

dotnet-portalclientemsdcombr/MSDPortal.Presentatio22n.Web/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

dotnet-portalclientemsdcombr/MSDPortal.Presentatio22n.Web/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

dotnet-portalclientemsdcombr/MSDPortal.Presentatio22n.Web/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
    Layout = "~/Views/Shared/AdminLTE/_Layout.cshtml";
}
<script src="~/scripts/js/fabric.min.js"></script>
<script src="~/adminlte/plugins/jquery/jquery.min.js"></script>
<script>

    $(document).ready(function () {


        

    });
}
</script>
<div class="container">
    <div class="row">
        <div class="col-4 pl-0">
            <h1 class="mt-2 primaryColor titlePage"> Resumo do Estoque</h1>
        </div>
        <div class="col">
            <div class=" ">
                <form class="form-inline " style="
               margin-top: 10px;
               ">
                    <div class="input-group input-group-sm pb-1 pt-1 pl-1 pr-1" style="
                  border: none;
                  border-radius: 20px;
                  background: #fff;
                  /* height: 30px; */
                  /* padding: 4px; */
                  ">
                        <input class="form-control form-control-navbar searchInput" type="search" placeholder="Buscar" aria-label="Search" style="
                     width: 280px;
                     border: none;
                     border-radius: 20px;
                     ">
                        <div class="input-group-append">
                            <button class="btn btn-navbar" type="submit">
                                <i class="fas fa-search" style="color:#0dbab1;"></i>
                            </button>
                        </div>
                    </div>

                </form>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-4 pl-0">
            <span style="color:#808080; font-weight:bold;"> Detalhes</span>
        </div>
    </div>
    
    
</div>
<!-- SEARCH FORM -->

dotnet-portalclientemsdcombr/MSDPortal.Presentatio22n.Web/Views/Produto/Create.cshtml
@model MSDPortal.Application.Entidades.Produto

<!DOCTYPE html>

@using (Html.BeginForm("Create", "Produto"))
{
@Html.AntiForgeryToken()

                <div class="container">
                    <div class="row">
                        <div class="col-9" style="left: 7px;">
                            <h1 class="mt-2 primaryColor titlePage">
                                Adicionar Produto
                            </h1>
                        </div>

                        <div class="col-3">
                            <ol class="breadcrumb float-sm-right">
                                <li class="breadcrumb-item"><a href="/Produto">Produto</a></li>
                                <li class="breadcrumb-item active"> Adicionar Produto</li>
                            </ol>
                        </div>
                    </div>
                    <hr /><br />
                </div>

                                <div class="container card mb-3">
                                    <div class="form-horizontal pt-1">
                                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                        <div class="form-group">
                                            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
                                            <div class="col-md-10">
                                                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                                                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
                                            </div>
                                        </div>

                                        <br />
                                        <div class="form-group">
                                            <div class="col-md-offset-2 col-md-10">
                                                <input type="submit" value="Salvar" class="btn btn-default" />
                                                @Html.ActionLink("Voltar", "Index", "Produto", new { @class = "btn btn-default" })
                                            </div>
                                        </div>
                                        <br /> <br />
                                    </div>
                                </div>
}

dotnet-portalclientemsdcombr/MSDPortal.Presentatio22n.Web/Views/Produto/Delete.cshtml
@model MSDPortal.Application.Entidades.Produto


<div class="container">
    <div class="container">
        <div class="row">
            <div class="col-9" style="left: 7px;">
                <h1 class="mt-2 primaryColor titlePage">
                    Tem certeza que deseja remover esse produto?
                </h1>
            </div>

            <div class="col-3">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Produto</a></li>
                    <li class="breadcrumb-item active">Remover Produto</li>
                </ol>
            </div>
        </div>
        <hr /><br />
    </div>

    @if (TempData["erro"] != null)
    {
<div class="col-md-12 col-sm-12">
    <div id="msg" class="alert alert-danger">@TempData["erro"]</div>
</div>}
    <br />

    <div class="container card mb-3">
        <div class="form-horizontal pt-1">
            <div>
                <dl class="dl-horizontal">
                    <dt>
                        @Html.DisplayNameFor(model => model.Nome)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Nome)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.DataCriacao)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.DataCriacao)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.DataAtualizacao)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.DataAtualizacao)
                    </dd>
                </dl>

                @using (Html.BeginForm())
                {
    @Html.AntiForgeryToken()

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Delete" class="btn btn-default" /> |
                            @Html.ActionLink("Voltar", "Index", "Produto", new { @class = "btn btn-default" })
                        </div>
                    </div>}
            </div>
        </div>
    </div>
</div>

dotnet-portalclientemsdcombr/MSDPortal.Presentatio22n.Web/Views/Produto/Edit.cshtml
@model MSDPortal.Application.Entidades.Produto

@using (Html.BeginForm("Edit", "Produto", FormMethod.Post, new { model = Model }))
{
@Html.AntiForgeryToken()

                <div class="container">
                    <div class="row">
                        <div class="col-9 " style="left: 7px;">
                            <h1 class="mt-2 primaryColor titlePage">
                                Editar Produto
                            </h1>
                        </div>

                        <div class="col-3">
                            <ol class="breadcrumb float-sm-right">
                                <li class="breadcrumb-item"><a href="/Produto">Produto</a></li>
                                <li class="breadcrumb-item active"> Editar Produto</li>
                            </ol>
                        </div>
                    </div>
                    <hr /><br />
                </div>

                                <div class="container card mb-3">
                                    <div class="form-horizontal pt-1">
                                        @Html.HiddenFor(model => model.Id)

                                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                        <div class="form-group">
                                            @Html.LabelFor(model => model.Nome, new { @class = "control-label col-md-2" })
                                            <div class="col-md-10">
                                                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                                                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
                                            </div>
                                        </div>


                                    </div>
                                    <br />
                                    <div class="container">
                                        <div class="col-md-offset-2 col-md-10">
                                            <input type="submit" value="Salvar" class="btn btn-default" />
                                            @Html.ActionLink("Voltar", "Index", "Produto", new { @class = "btn btn-default" })
                                        </div>
                                        <br /> <br />
                                    </div>
                                </div>}

dotnet-portalclientemsdcombr/MSDPortal.Presentatio22n.Web/Views/Produto/Index.cshtml
@model IEnumerable<MSDPortal.Application.Entidades.Produto>

@{ ViewBag.Title = "Home Page";
                Layout = "~/Views/Shared/AdminLTE/_Layout.cshtml"; }

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

<script src="~/adminlte/plugins/datatables/jquery.dataTables.js" defer></script>

<link href="~/adminlte/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css" rel="stylesheet" />
<script src="~/adminlte/plugins/datatables-bs4/js/dataTables.bootstrap4.js" defer></script>

<script>$(document).ready(function () {
        $('#tabelaDestaques').DataTable();
        $('#thRemoveClass').removeClass("sorting");
    });</script>
<div class="container  ">
    <div class="row">

        <div class="col pl-0">
            <h1 class="mt-2 primaryColor titlePage">  Produto</h1>
        </div>
        <div class="col">

        </div>
    </div>

    <div class="row">
        <div class="col-1 mt-4 mb-3 pl-0">

            <a asp-action="Create" class="btn    " href="@Url.Action("Create", "Produto")" style="color: white;background: #169994!important;/* width: 200px; *//* width: auto; */width: 100%;">
                Novo<i class="fa fa-plus" aria-hidden="true" style="  padding-inline-start: 10px;
"></i>
            </a>
        </div>
    </div>
    <div class="row">
        <table class="table dxbs-fixed table table-bordered table-sm table-striped" id="tabelaDestaques" style="background:#fff;width:100% ">
            <thead>
                <tr>

                    <th>
                        Nome
                    </th>
                    <th id="thRemoveClass" width="16%">
                    </th>
                </tr>
            </thead>
            <tbody>

            @if(Model != null)
            { 
                foreach (var item in Model)
                {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Nome)
        </td>

        <td class="dxbs-cmd-cell tdGrid text-center" width="16%">
            <a asp-action="Edit" asp-route-id="@item.Id" href="@Url.Action("Edit", "Produto", new { id = item.Id })" class="btn-sm btn-link dxbs-button" data-toggle="tooltip" data-placement="top" title="Editar"><i class="far fa-edit"></i></a>
            <a asp-action="Delete" asp-route-id="@item.Id" href="@Url.Action("Delete", "Produto", new { id = item.Id })" class="btn-sm btn-link dxbs-button" data-toggle="tooltip" data-placement="top" title="Excluir"><i class="far fa-trash-alt"></i> </a>
        </td>
    </tr>}
            }
            </tbody>

        </table>
    </div>
</div>

dotnet-portalclientemsdcombr/MSDPortal.Presentatio22n.Web/Views/Shared/AdminLTE/_Footer.cshtml
 


    <footer class="main-footer">
        <div class="social-media-footer" style="margin-top:10px">

            <a href="#"><i class="fab fa-instagram" style="color:#000; padding:10px"></i></a>
            <a href="#"><i class="fab fa-twitter" style="color:#000;padding:10px;"></i></a>
            <a href="#"><i class="fab fa-facebook-f" style="color:#000;padding:10px;"></i></a>

        </div>
        <div class="float-right d-none d-sm-block logo-footer" style="margin-bottom:5px">
            <img width="132" height="65" style="margin:auto" src="https://www.msd-saude-animal.com.br/wp-content/uploads/sites/55/2020/08/msd-saude-animal-logo.png" class="custom-logo" alt="MSD Salud Animal Brazil" srcset="https://www.msd-saude-animal.com.br/wp-content/uploads/sites/55/2020/08/msd-saude-animal-logo.png 532w, https://www.msd-saude-animal.com.br/wp-content/uploads/sites/55/2020/08/msd-saude-animal-logo.png?resize=300,149 300w" sizes="(max-width: 532px) 100vw, 532px">
        </div>

    </footer>

dotnet-portalclientemsdcombr/MSDPortal.Presentatio22n.Web/Views/Shared/AdminLTE/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta http-equiv="x-ua-compatible" content="ie=edge" />
    @*<link href="~/LFW20/Styles/site.css" rel="stylesheet" />*@
    <title>MSD Portal</title>
    @Html.Partial("AdminLTE/_Styles")
    <link rel="stylesheet" href="~/Content/Site.css" />
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@10"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
 
    <script src="//cdn.jsdelivr.net/npm/promise-polyfill@8/dist/polyfill.js"></script>
    @*<script src="~/adminlte/js/adminlte.js"></script>*@
   
</head>

<body class="hold-transition sidebar">

    <div class="wrapper">
        @Html.Partial("AdminLTE/_TopNavigation")
        @Html.Partial("AdminLTE/_MainNavigation")
        <div class="content-wrapper">
            <div class="content-header">
                <div class="container-fluid">
                    <div class="row mb-2">
                        <div class="col-sm-6">
                            <h1 class="m-0 text-dark"></h1>
                        </div>

                    </div>
                </div>
            </div>
            <div class="content">
                <div class="container-fluid">
                    @RenderBody()
                </div>
            </div>

        </div>
        <aside class="control-sidebar control-sidebar-dark">
            <div class="p-3">
                <a class="nav-link" data-widget="control-sidebar" href="#">Toggle Control Sidebar</a>

            </div>
        </aside>
        @Html.Partial("AdminLTE/_Footer")
    </div>
    @Html.Partial("AdminLTE/_Scripts")

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/adminlte/js")
    @Scripts.Render("~/bundles/inputmask")

    @RenderSection("scripts", required: false)
</body>
</html>

dotnet-portalclientemsdcombr/MSDPortal.Presentatio22n.Web/Views/Shared/AdminLTE/_LayoutNotLogged.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta http-equiv="x-ua-compatible" content="ie=edge" />
    @*<link href="~/LFW20/Styles/site.css" rel="stylesheet" />*@
    <title>MSD Portal</title>
    @Html.Partial("AdminLTE/_Styles")
    <link rel="stylesheet" href="~/Content/Site.css" />

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="~/adminlte/js/adminlte.js"></script>
</head>
@{
    if (Context.User.Identity.IsAuthenticated)
    {
        Layout = "_Layout";
    }
    else
    {
        Layout = "../_NotLogged/_NotLoggedLayout";
    }
}
<body class="hold-transition sidebar">
    <div class="wrapper">
        @Html.Partial("AdminLTE/_TopNavigation")
        @Html.Partial("AdminLTE/_MainNavigation")
        <div class="content-wrapper">
            <div class="content-header">
                <div class="container-fluid">
                    <div class="row mb-2">
                        <div class="col-sm-6">
                            <h1 class="m-0 text-dark"></h1>
                        </div>

                    </div>
                </div>
            </div>
            <div class="content">
                <div class="container-fluid">
                    @RenderBody()
                </div>
            </div>
        </div>
        <aside class="control-sidebar control-sidebar-dark">
            <div class="p-3">
                <a class="nav-link" data-widget="control-sidebar" href="#">Toggle Control Sidebar</a>

            </div>
        </aside>
        @Html.Partial("AdminLTE/_Footer")
    </div>
    @Html.Partial("AdminLTE/_Scripts")

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/adminlte/js")
    @Scripts.Render("~/bundles/inputmask")

    @RenderSection("scripts", required: false)
</body>
</html>

dotnet-portalclientemsdcombr/MSDPortal.Presentatio22n.Web/Views/Shared/AdminLTE/_MainNavigation.cshtml
 
    <aside class="main-sidebar  sidebarColor elevation-4">

        <div class="mt-2 pt-1 mb-0 d-flex" style="
   
">

            
            <img width="110" height="38" style="margin:auto" src="~/Content/images/45009.png"
                 class="custom-logo" alt="MSD Salud Animal Brazil"   sizes="(max-width: 532px) 100vw, 532px">
        </div>
        <div class="user-panel mt-2 pb-1 mb-1   d-flex">

        </div>
        <div class="sidebar sidebarT">

   

            <nav class="mt-2">

                <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                    <li class="nav-item ">

                        <a href="@Url.Action("Index", "Produto")" class="nav-link">
                            Produtos
                        </a>
                    </li>
                </ul>
            </nav>
        </div>
    </aside>
 

dotnet-portalclientemsdcombr/MSDPortal.Presentatio22n.Web/Views/Shared/AdminLTE/_Scripts.cshtml
<script src="~/adminlte/plugins/jquery/jquery.min.js"></script>
<script src="~/adminlte/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
<script src="~/adminlte/js/adminlte.min.js"></script>


<script>
    $(document).ready(function () {
        $("#telefone").inputmask("mask", { "mask": "(99) 9999-99999" });
        $("#cpf").inputmask("mask", { "mask": "999.999.999-99" }, { reverse: true });
        $("#cnpj").inputmask("mask", { "mask": "99.999.999/9999-99" }, { reverse: true });
        $("#cep").inputmask("mask", { "mask": "99999-999" });
        $("#nascimento").inputmask("mask", { "mask": "99/99/9999" });
        $("#preco").inputmask("mask", { "mask": "999.999,99" }, { reverse: true });
        $("#valor").inputmask("mask", { "mask": "#.##9,99" }, { reverse: true });
        $("#ip").inputmask("mask", { "mask": "999.999.999.999" });
    });
</script>

dotnet-portalclientemsdcombr/MSDPortal.Presentatio22n.Web/Views/Shared/AdminLTE/_TopNavigation.cshtml
 <!-- Navbar -->
<nav class="main-header navbar navbar-expand navbar-white   pb-3" style="height:66px; ">
    <!-- Left navbar links -->
    <ul class="navbar-nav" style="margin:auto;">
        <li class="nav-item">
            @* <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>*@
        </li>
        <li class="nav-item d-none d-sm-inline-block" style="padding-right:45px; letter-spacing:1px;">
            <a id="linkHome" href="@Url.Action("Index", "Produto", new {  })" class="menuTop-link nav-link text-uppercase font-weight-bold ">Produtos</a>
        </li>
    </ul>


    <!-- Right navbar links -->
    @*<div class="navbar-nav mr-auto">
        <div class="saudacao" style="width:100%; font-size: 9pt;">
            <div class="primeiraLinha" style="">
                <span style="color:#999; font-weight:bold"> OLÁ,</span>
                <span style="color:#0dbab1; font-weight:bold;"> </span>
            </div>
            <span style="color:#999;">LOJA,</span>
            <span style="color:#999; font-weight:bold;">xxx</span>
        </div>
    </div>*@
</nav>
<!-- /.navbar -->




 <script>
     window.onload = function () {
    if(document.location.pathname === "/"){
        document.querySelector("#linkHome").classList.add("menuTop-link-active");
      }
          
}
   

 </script>


 